### ISSUE TITLE
Inserir suporte dos mecanismos de verificação do Polygon

### ISSUE THREAD

**Issue by danielsaad** [danielsaad/ds-contest-tools#5]
Mecanismos de verificação como:
- Checagem de testes replicados
- Checagem do veredito do checker através da solução esperada

precisam ser implementados.

**Comment by loioladev** [comment]
- Checagem de testes repetidos foi iniciada a partir do merge #19 e finalizada logo depois.
- Checagem do veredito do checker através da solução esperada foi realizada a partir da branch dev-silent-checker e está sendo continuamente melhorada para melhorar a visualização do resultado.
